<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CardTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardTypeRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT cT
                  FROM AppBundle:CardType cT'
            )
            ->getResult();
    }

    public function findAllOrderedByCtDescriptionAsc()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT cT
                  FROM AppBundle:CardType cT
                  ORDER BY cT.ctDescription ASC'
            )
            ->getResult();
    }
}
