<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends EntityRepository
{
    public function findAllByTaleId($taleId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c
                  FROM AppBundle:Card c JOIN c.cardType ct JOIN c.actions a JOIN a.sequence s JOIN s.tale t
                  WHERE t.id = :taleId'
            )
            ->setParameter('taleId', $taleId)
            ->getResult();
    }
}