<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
    public function findAllOrderedById()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT l FROM AppBundle:Log l ORDER BY l.id ASC'
            )
            ->getResult();
    }
}
