<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
    public function deleteOneById($id)
    {
        $this->getEntityManager()
            ->createQuery(
                'DELETE FROM AppBundle:Log l WHERE l.id = :id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}
