<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SequenceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceTypeRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT sT
                  FROM AppBundle:SequenceType sT'
            )
            ->getResult();
    }
}
