<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t
                  FROM AppBundle:Type t'
            )
            ->getResult();
    }

    public function findAllOrderedByTypeDescriptionAsc()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t
                  FROM AppBundle:Type t
                  ORDER BY t.typeDescription ASC'
            )
            ->getResult();
    }
}
