<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findOneByTaleId($taleId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:Tale t, AppBundle:User u WHERE t.userId = u.id AND t.id = :taleId'
            )
            ->setMaxResults(1)
            ->setParameter('taleId', $taleId)
            ->getResult();
    }
}
