<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findOneByTale($taleTitle)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:Tale t, AppBundle:User u WHERE t.userId = u.id AND t.taleTitle = :taleTitle'
            )
            ->setParameter('taleTitle', $taleTitle)
            ->getResult();
    }
}
