<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findOneByTaleId($taleId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u JOIN u.tales t WHERE t.id = :taleId'
            )
            ->setMaxResults(1)
            ->setParameter('taleId', $taleId)
            ->getResult();
    }

    public function deleteOneById($id)
    {
        $this->getEntityManager()
            ->createQuery(
                'DELETE FROM AppBundle:User u WHERE u.id = :id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}
