<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLikeRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT uL
                  FROM AppBundle:UserLike uL'
            )
            ->getResult();
    }

    public function deleteById($taleId, $userId)
    {
        $this->getEntityManager()
            ->createQuery(
                'DELETE
                  FROM AppBundle:UserLike uL
                  WHERE uL.tale = :taleId AND uL.user = :userId'
            )
            ->setParameter('taleId', $taleId)
            ->setParameter('userId', $userId)
            ->getResult();
    }
}
